development:
  morphology: stem_en
  enable_star: true
  min_infix_len: 3
test:
  morphology: stem_en
  enable_star: true
  min_infix_len: 3
production:
  morphology: stem_en
  enable_star: true
  min_infix_len: 3
